services:
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - ./core/.env

  proxy-server:
    build:
      context: ./proxy-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./proxy-server/.env

  redis:
    container_name: deployit-redis
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
    restart: always
