services:
  redis:
    container_name: deployit-redis
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always
    volumes:
      - redis-data:/data
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - ./core/.env

  proxy-server:
    build:
      context: ./proxy-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./proxy-server/.env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://xyz.localhost:8000"]
      interval: 5m
      timeout: 3s
      retries: 3
      start_period: 5s

volumes:
  redis-data: