import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/Navbar";
import AppWrapper from "../providers/app-wrapper";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AppWrapper>
          <Navbar />
          {children}
          <Toaster />
        </AppWrapper>
      </body>
    </html>
  );
}
