#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd core && npm run format && npx tsc -b && npm run build
cd ../docker-builder npm run format && npm run build
cd ../proxy-server && npm run format && npm run build