#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd core && pnpm run format && pnpm run build
cd "../docker-builder "pnpm run format && pnpm run build
cd "../proxy-server" && pnpm run format
cd .. && git add .